// Enhanced Dashboard with AI Insights and Activity Feed
import React from 'react';
import { UserProfile } from '../../../types';
import { usePlatformStore } from '../../store/platformStore.js';
import { useAgent } from '../../hooks/useAgent.js';
import { ActivityItem, Metric } from '../../types/platform.js';

interface EnhancedDashboardProps {
  user: UserProfile;
  toolStats: { [key: string]: { usage: number } };
  onSelectTool: (tool: any) => void;
  onSelectRecipe: (recipe: any) => void;
  onLogout: () => void;
  onOpenProfile: () => void;
  onOpenSettings: () => void;
  onCompleteOnboarding: () => void;
}

export default function EnhancedDashboard({
  user,
  toolStats,
  onSelectTool,
  onSelectRecipe,
  onLogout,
  onOpenProfile,
  onOpenSettings,
  onCompleteOnboarding,
}: EnhancedDashboardProps) {
  const { activities, metrics, quickActions } = usePlatformStore();
  const { suggestions, isConnected } = useAgent(user, {
    currentPage: 'dashboard',
  });

  // AI Insights (mock for now, will be generated by agent)
  const aiInsights = [
    {
      id: 'insight-1',
      title: 'Workflow Optimization',
      description: '3 workflows can be automated to save 5 hours/week',
      action: 'View Workflows',
    },
    {
      id: 'insight-2',
      title: 'Data Quality Alert',
      description: '12 leads need enrichment in Baserow',
      action: 'Enrich Leads',
    },
    {
      id: 'insight-3',
      title: 'Productivity Tip',
      description: 'Your team used Market Insight AI 15 times this week',
      action: 'View Analytics',
    },
  ];

  return (
    <div className="min-h-screen bg-brand-bg text-white p-6">
      <div className="max-w-7xl mx-auto space-y-6">
        {/* Header */}
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-3xl font-bold text-white">Dashboard</h1>
            <p className="text-brand-text-muted mt-1">Welcome back, {user.name}</p>
          </div>
          <div className="flex items-center gap-2">
            <div className={`w-2 h-2 rounded-full ${isConnected ? 'bg-green-500' : 'bg-red-500'}`}></div>
            <span className="text-sm text-brand-text-muted">
              Agent {isConnected ? 'Connected' : 'Disconnected'}
            </span>
          </div>
        </div>

        {/* AI Insights Panel */}
        <div className="bg-brand-bg-secondary border border-brand-border rounded-lg p-6">
          <h2 className="text-xl font-bold text-white mb-4 flex items-center gap-2">
            <span className="w-8 h-8 bg-gradient-to-br from-brand-lemon to-brand-forest rounded-full flex items-center justify-center text-white font-bold text-sm">
              AI
            </span>
            AI Insights & Recommendations
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            {aiInsights.map(insight => (
              <div
                key={insight.id}
                className="bg-brand-bg-tertiary border border-brand-border rounded-lg p-4 hover:border-brand-lemon transition cursor-pointer"
              >
                <h3 className="font-semibold text-white mb-2">{insight.title}</h3>
                <p className="text-sm text-brand-text-muted mb-3">{insight.description}</p>
                <button className="text-sm text-brand-lemon hover:text-brand-lemon-light font-semibold">
                  {insight.action} →
                </button>
              </div>
            ))}
          </div>
        </div>

        {/* Main Content Grid */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Activity Feed */}
          <div className="lg:col-span-2 bg-brand-bg-secondary border border-brand-border rounded-lg p-6">
            <h2 className="text-xl font-bold text-white mb-4">Recent Activity</h2>
            <div className="space-y-3">
              {activities.length > 0 ? (
                activities.slice(0, 10).map(activity => (
                  <div
                    key={activity.id}
                    className="bg-brand-bg-tertiary border border-brand-border rounded-lg p-3"
                  >
                    <div className="flex items-center justify-between">
                      <div>
                        <p className="text-sm text-white">{activity.action}</p>
                        <p className="text-xs text-brand-text-muted">
                          {activity.user} • {new Date(activity.timestamp).toLocaleString()}
                        </p>
                      </div>
                      <span className="text-xs px-2 py-1 bg-brand-bg rounded text-brand-text-muted">
                        {activity.type}
                      </span>
                    </div>
                  </div>
                ))
              ) : (
                <div className="text-center py-8 text-brand-text-muted">
                  No recent activity
                </div>
              )}
            </div>
          </div>

          {/* Metrics & Quick Actions */}
          <div className="space-y-6">
            {/* Metrics */}
            <div className="bg-brand-bg-secondary border border-brand-border rounded-lg p-6">
              <h2 className="text-xl font-bold text-white mb-4">Metrics</h2>
              <div className="space-y-4">
                {metrics.length > 0 ? (
                  metrics.map(metric => (
                    <div key={metric.id}>
                      <div className="flex items-center justify-between mb-1">
                        <span className="text-sm text-brand-text-muted">{metric.name}</span>
                        <span className="text-lg font-bold text-white">
                          {metric.value} {metric.unit || ''}
                        </span>
                      </div>
                      {metric.change && (
                        <div className={`text-xs ${metric.change > 0 ? 'text-green-500' : 'text-red-500'}`}>
                          {metric.change > 0 ? '+' : ''}{metric.change}%
                        </div>
                      )}
                    </div>
                  ))
                ) : (
                  <div className="text-sm text-brand-text-muted">
                    No metrics available
                  </div>
                )}
              </div>
            </div>

            {/* Quick Actions */}
            {quickActions.length > 0 && (
              <div className="bg-brand-bg-secondary border border-brand-border rounded-lg p-6">
                <h2 className="text-xl font-bold text-white mb-4">Quick Actions</h2>
                <div className="space-y-2">
                  {quickActions.map(action => (
                    <button
                      key={action.id}
                      onClick={action.action}
                      className="w-full text-left px-4 py-2 bg-brand-bg-tertiary border border-brand-border rounded-lg hover:border-brand-lemon transition"
                    >
                      <span className="text-sm text-white">{action.label}</span>
                    </button>
                  ))}
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}

